### ISSUE TITLE
股票代码重叠时，指定前缀也会导致返回结果部分丢失

### ISSUE THREAD

**Issue by cszhe** [shidenggui/easyquotation#11]
譬如我想同时拿到上证指数和平安银行的价格，代码如下，但是返回的数据集中会把stock list中的靠前一个股票给覆盖掉。鉴于上证的指数与深圳的股票代码大量重叠，这不是个例，是否可以改成返回的dict中的key也是带前缀的股票代码？

In[2]: import easyquotation as eq
In[3]: qq = eq.use('qq')
In[4]: b = qq.stocks(['sh000001', 'sz000001'])
In[5]: b
Out[5]: 
{'000001': {'PB': 0.87,
  'PE': 6.56,
  'ask1': 10.25,
  'ask1_volume': 239200,
  'ask2': 10.26,
  'ask2_volume': 552000,
  'ask3': 10.27,
  'ask3_volume': 582900,
  'ask4': 10.28,
  'ask4_volume': 289600,
  'ask5': 10.29,
  'ask5_volume': 441700,
  'ask_volume': 8754200.0,
  'bid1': 10.24,
  'bid1_volume': 242200,
  'bid2': 10.23,
  'bid2_volume': 223700,
  'bid3': 10.22,
  'bid3_volume': 594400,
  'bid4': 10.21,
  'bid4_volume': 710900,
  'bid5': 10.2,
  'bid5_volume': 1003700,
  'bid_volume': 8036600,
  'close': 10.27,
  'code': '000001',
  'datetime': datetime.datetime(2016, 5, 30, 11, 30, 15),
  'high': 10.27,
  'high_2': 10.27,
  'low': 10.2,
  'low_2': 10.2,
  'name': '平安银行',
  'now': 10.24,
  'open': 10.25,
  'turnover': 0.14,
  'unknown': '',
  'volume': 16790800.0,
  '价格/成交量(手)/成交额': '10.24/165561/169371889',
  '总市值': 1465.21,
  '成交量(手)': 16790800,
  '成交额(万)': 171780000.0,
  '振幅': 0.68,
  '最近逐笔成交': '11:29:57/10.24/48/S/49152/17511|11:29:54/10.25/6/B/6150/17507|11:29:51/10.25/2083/B/2135075/17496|11:29:48/10.25/1/B/1025/17486|11:29:36/10.25/20/B/20500/17464|11:29:33/10.25/17/B/17425/17458',
  '流通市值': 1248.52,
  '涨停价': 11.3,
  '涨跌': -0.03,
  '涨跌(%)': -0.29,
  '跌停价': 9.24}}

**Comment by shidenggui** [comment]
这个确实是当时的设计缺陷，现在如果带前缀返回的就破坏了原来的 api，除非是返回双份

**Comment by cszhe** [comment]
可否增加个新API，返回带前缀的代码。现在的API接口也照样保留，并且可以通过调用新API实现。跟Windows中那些CreateFile, CreateFileEx类似。

**Comment by shidenggui** [comment]
@cszhe 更新了新版本， 新浪和qq添加了 all_market 方法，获取的值是带前缀的
