### ISSUE TITLE
这段代码有缺陷

### ISSUE THREAD

**Issue by chenyangguang** [shidenggui/easyquotation#17]
max_num = 800 
....
for range_start in range(request_num):
            num_start = self.max_num * range_start
            num_end = self.max_num * (range_start + 1)
            request_list = ','.join(stock_with_exchange_list[num_start:num_end])
            stock_list.append(request_list)

num_start 和num_end 最后将超出 request_num ， 也就是说会远超出stock_with_exchange_list的长度。这样结尾拼接的时候，其实你是多出来很多的 ‘，’， 的。

**Comment by shidenggui** [comment]
num_start 超过回直接报错， num_end 超过并没有影响。所以并不会有很多 ','
