### ISSUE TITLE
关于sina模块字符串解析的问题

### ISSUE THREAD

**Issue by wu9961** [shidenggui/easyquotation#2]
#data.txt是我执行all之后将code和name打印出来写的文件
其中房地产a，特力b，恒生h股解析发生问题
，目前还没定位原因
[data.txt](https://github.com/shidenggui/easyquotation/files/121332/data.txt)

**Comment by shidenggui** [comment]
我试了下没问题，你用目前的版本再看看

**Comment by wu9961** [comment]
该问题涉及到编码问题，python2我用的是urllib2，获取的数据编码可能和aiohttp不同，现在我已经解决问题了，先decode("gbk")再encode("utf-8")就可以解决了
