### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by shenyp09** [shidenggui/easyquotation#21]
SyntaxError: Non-ASCII character '\xe7' in file /tmp/easy_install-icYjiU/easyquotation-0.4.4/easyquotation/api.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by shidenggui** [comment]
Python版本？

**Comment by shenyp09** [comment]
我去，居然要求3.5+...完全没注意到，sorry
