### ISSUE TITLE
现在只能取单个行情了吗,ALL 不行了?

### ISSUE THREAD

**Issue by whcobra** [shidenggui/easyquotation#23]
现在只能取单个行情了吗,ALL 不行了?

**Comment by shidenggui** [comment]
看了下，是 aiohttp 升级导致的，目前 aiohttp 会对默认 URL 做 urlencode， 而且没法关闭，导致 url 中的`,`被转义，从而导致新浪报错。目前更新版本限制 aiohttp 库的最高版本了。
你可以用 `pip install 'aiohttp<=1.0.5` 来降低 aiohttp 到可用版本
