### ISSUE TITLE
当网络连接有问题时 如何自动重试获取行情而不是报错？

### ISSUE THREAD

**Issue by niutao3** [shidenggui/easyquotation#27]
致作者：近日测试行情出现如下报错，可能网络连接不好，如何让行情获取不报错，而是自动重试，该参数可否调节？
ClientOSError: [Errno 11002] Cannot connect to host hq.sinajs.cn:80 ssl:False [getaddrinfo failed]

**Comment by shidenggui** [comment]
这个你可以在外面处理下，因为重试策略可能每个人都不一样

**Comment by niutao3** [comment]
感谢您的回复，已在外部解决。
