### ISSUE TITLE
leverfun的api是通过什么方法获得的？

### ISSUE THREAD

**Issue by Rockyzsu** [shidenggui/easyquotation#28]
请问大神这个是怎么获取得到的？ 抓包还是官方就有？
如果是官方的，请问有api 文档吗

**Comment by yutiansut** [comment]
https://app.leverfun.com/timelyInfo/timelyOrderForm

**Comment by Rockyzsu** [comment]
@yutiansut 
谢谢！ 我知道这个链接，不过只是想知道你们是知道这个链接可以获取到level2的数据的？ 是不是这个api曾经公开过？

**Comment by shidenggui** [comment]
我知道这个api是来自于一个其他github项目，应该是nodejs的，具体记不清了

**Comment by Rockyzsu** [comment]
@shidenggui 好的。 谢谢！
