### ISSUE TITLE
请问通过Sina得到的全市场是Level1还是Level2数据？

### ISSUE THREAD

**Issue by 4ever911** [shidenggui/easyquotation#31]
目前在用另外一个基于weboscket 的Sina Level2代码， 使用起来不稳定，所以考虑要不要用轮询的方式来用easyquotation，请问目前这个取到的值是Level2的吗？ 会延时几秒吗？

**Comment by yutiansut** [comment]
sina l2本来就是socket推过来的吧

**Comment by shidenggui** [comment]
Level1
