### ISSUE TITLE
lever_fun取数据的问题

### ISSUE THREAD

**Issue by wangxu666** [shidenggui/easyquotation#33]
1.aiohttp已经不支持get了，目前是request，aiohttp.request(url=Leverfun.stock_api,params=params,method='GET') 
2.两次取一个ID的实时level2，第二次包含第一次的结果，感觉像是bug
if __name__ == '__main__':
    q = Leverfun()
    q.real('000001')
    print(q.stocks_dict)
    q.real('000005')
    print(q.stocks_dict)

第二次print 包含第一次的数据

**Comment by shidenggui** [comment]
leverfun 接口已经失效
