### ISSUE TITLE
leverfun是不是不能用了？

### ISSUE THREAD

**Issue by 4ever911** [shidenggui/easyquotation#36]
{"code":0,"data":{"match":0.0,"buyPankou":null,"sellPankou":null,"preClose":null,"type":2},"message":"","success":true}

**Comment by 4ever911** [comment]
另外 aiohttp 的新版本不能用get，需要构建session 来request

**Comment by colay616** [comment]
这版本可以更新下吗，

**Comment by shidenggui** [comment]
leverfun 接口已经失效
