### ISSUE TITLE
内存消耗太大

### ISSUE THREAD

**Issue by xiongjingan** [shidenggui/easyquotation#40]
现在的easyquotation,取数据很耗内存，每取一次全场数据就要消耗3M内存，还不会自动释放内存。有没有办法解决内存消耗大的问题？

**Comment by xiongjingan** [comment]
现在的easyquotation,取数据很耗内存，每取一次全场数据就要消耗3M内存，还不会自动释放内存。有没有办法解决内存消耗大的问题？
代码如下：
import easyquotation
import tushare as ts
import time
quotation=easyquotation.use('qq')
df=ts.get_day_all()
code=list(df.code)
while True:
data=quotation.stocks(code)
time.sleep(2)

**Comment by favoyang** [comment]
大概是 commit 12ac33c (v0.5.3) 引入的Bug。get_stock_data新的实现，每次都会生成一个新的ThreadPool object, 也没有close，导致了内存泄露。考虑到建立thread的开销（比如分配8MB的stack size），每次调用get_stock_data都创建新的thread pool似乎欠妥。简单的将ThreadPool的创建过程移出get_stock_data，并赋予固定大小的pool size，就可以解决这个问题。这样做了get_stock_data是否还是thread safe有待研究。

```
def get_stock_data(self, stock_list, **kwargs):
    pool = ThreadPool(len(stock_list))
    res = pool.map(self.get_stocks_by_range, stock_list)
```

@xiongjingan, 可以暂时使用0.5.2版本。(`pip install easyquotation==0.5.2`).

**Comment by shidenggui** [comment]
fix by 8186cd20ce59b0f2b4e6c221432d930f9cdf3f30
