### ISSUE TITLE
timeKline 不能用

### ISSUE THREAD

**Issue by cshlxm** [shidenggui/easyquotation#44]
看了下，是stock_api 的地址问题，改了下就可以了。当然我这么改会影响其它接口...
![_20180425130033](https://user-images.githubusercontent.com/4603098/39227032-ec56b876-4888-11e8-9de9-18546391bc3d.png)
![_20180425130039](https://user-images.githubusercontent.com/4603098/39227033-ecaec37c-4888-11e8-9dea-aa383dd01e3d.png)

**Comment by lynic** [comment]
In [3]: eq.real(['603828'], prefix=True)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-7c9c91b06703> in <module>()
----> 1 eq.real(['603828'], prefix=True)

/usr/local/anaconda3/envs/trader/lib/python3.5/site-packages/easyquotation/basequotation.py in real(self, stock_codes, prefix)
     74
     75         stock_list = self.gen_stock_list(stock_codes)
---> 76         return self.get_stock_data(stock_list, prefix=prefix)
     77
     78     def market_snapshot(self, prefix=False):

/usr/local/anaconda3/envs/trader/lib/python3.5/site-packages/easyquotation/basequotation.py in get_stock_data(self, stock_list, **kwargs)
     96         """获取并格式化股票信息"""
     97         res = self._fetch_stock_data(stock_list)
---> 98         return self.format_response_data(res, **kwargs)
     99
    100     def _fetch_stock_data(self, stock_list):

/usr/local/anaconda3/envs/trader/lib/python3.5/site-packages/easyquotation/timekline.py in format_response_data(self, rep_data, prefix)
     29             # res like ['min_data="', 'date:180413', '0930 11.64 29727', '0931 11.65 52410']
     30             res = re.split(r'\\n\\\n', stock_detail)
---> 31             date = '20{}'.format(res[1][-6:])
     32             time_data = list(
     33                 d.split() for d in res[2:] if re.match(r'\d{4}', d))

IndexError: list index out of range

**Comment by shidenggui** [comment]
close by db16e814ca2ab7ae72dc4467a4a8816fdd266999
