### ISSUE TITLE
腾讯分时数据，一次可以查询几支股票？

### ISSUE THREAD

**Issue by r41350** [shidenggui/easyquotation#56]
你好，
请问，为什么一次只能得到前四支股票数据
import easyquotation
quotation = easyquotation.use("timekline")
codelist=['600220', '000533', '002400', '002077','000565','000009','002179']
data = quotation.real(codelist, prefix=False)
print(data.keys())

是不是调用太频繁，需要time.sleep( )之类的？

**Comment by shidenggui** [comment]
一次一条，没有全部返回是代码 bug，已经修复。
