### ISSUE TITLE
查找港股指数数据

### ISSUE THREAD

**Issue by yuanmf08** [shidenggui/easyquotation#58]
def format_response_data(self, rep_data, **kwargs):
        stocks_detail = "".join(rep_data)

        stock_dict = {}
        for raw_quotation in re.findall(r'v_r_hk\d+=".*?"', stocks_detail):
            quotation = re.search('"(.*?)"', raw_quotation).group(1).split("~")
            stock_dict[quotation[2]] = dict(
                lotSize=float(quotation[0]),
                name=quotation[1],
                price=float(quotation[3]),
                lastPrice=float(quotation[4]),
                openPrice=float(quotation[5]),
                amount=float(quotation[6]),
                time=quotation[30],
                dtd=float(quotation[32]),
                high=float(quotation[33]),
                low=float(quotation[34]),
            )

查找指数数据时，因为匹配的是数字r'v_r_hk\d，所以无法读出HSI等指数的数据，建议改为匹配文字
另外可以加入daily return项目dtd=float(quotation[32]),

**Comment by shidenggui** [comment]
close by 43658a51118e02fcbc3e9fb3f6712f4212859094

**Comment by KitKanWong** [comment]
@yuanmf08 大大請問現在要怎麼拿到恆指? 

quotation = easyquotation.use("hkquote")
# data = quotation.stocks(['hk00001'], prefix=True)
data = quotation.stocks(['hkHSI'], prefix=True) 

這樣不行呀，請教下

**Comment by shidenggui** [comment]
@KitKanWong 指数没支持，这个pr只是加了下 dtd
