### ISSUE TITLE
Regular match bug in sina api

### ISSUE THREAD

**Issue by chasingegg** [shidenggui/easyquotation#60]
有些股票名称中有空格，正则匹配时会出bug。例如`sz000002`股票新浪api返回结果是
```
var hq_str_sz000002="万 科Ａ,26.850,26.920,26.700,27.070,26.700,26.700,26.710,20014595,537589152.850,189399,26.700,18400,26.690,47300,26.680,6000,26.670,66800,26.660,800,26.710,12600,26.720,5000,26.730,2000,26.740,22000,26.750,2019-05-31,15:00:03,00";
```
得到的是“万 科A”，导致结果出错。一个比较丑陋的方式是去除返回字符串中的空格，在`basequotation.py`中作如下修改。
```Python
return [re.sub(r'\s', "", d) for d in res if d is not None]
```

**Comment by 0dingdong0** [comment]
把正则改成：

    grep_detail = re.compile(
        r'(\d+)="([^,]+)%s%s'
        % (r",([\.\d]+)" * 29, r",([-\.\d:]+)" * 2)
    )
    grep_detail_with_prefix = re.compile(
        r'(\w{2}\d+)="([^,]+)%s%s'
        % (r',([\.\d]+)' * 29, r',([-\.\d:]+)' * 2)
    )
就好了

**Comment by shidenggui** [comment]
fix by #71

**Comment by izhangmh** [comment]
#71 没解决本问题啊
