### ISSUE TITLE
获取全部股票时，返回数据不全，原因是

### ISSUE THREAD

**Issue by ymli1981** [shidenggui/easyquotation#75]
stocks_detail = "".join(rep_data)
grep_str = self.grep_detail_with_prefix if prefix else self.grep_detail
这两句中间要加一句
stocks_detail = stocks_detail.replace(" ","")
否则如果股票名字中有空格，就会被过滤掉

**Comment by Wendroff** [comment]
非常感谢，我也被这个问题困扰！这里给一个供开发者调试的具体案例：000997 新大陆

**Comment by Wendroff** [comment]
我改了一下感觉不太对，感觉应该还是得改正则表达式

**Comment by Wendroff** [comment]
我也遇到了这个问题。另外想请教一下开发者，正则表达式为什么不匹配双引号？然后直接把里里面的东西split by ，感觉就行了。

**Comment by shidenggui** [comment]
@Wendroff 那样也可以，但是只是觉得正则也挺简单的。
