### ISSUE TITLE
某些港股日k线图獲取錯誤

### ISSUE THREAD

**Issue by KitKanWong** [shidenggui/easyquotation#78]
現在接口默認使用qfqday來獲取數據，但現在很多新股的KEY都是day
比如小米:
請求:
http://web.ifzq.gtimg.cn/appstock/app/hkfqkline/get?_var=kline_dayqfq&param=hk01810,day,,,350,qfq&r=0.7773272375526847
返回:
line_dayqfq={"code":0,"msg":"","data":{"hk01810":{"day":[["2018-11-07","13.040","13.300","13.660","13.040","31656661.00",{},"0.00","42546.00",""],["2018-11-08","13.700","13.720","14.120","13.500","57147505.00",{},"0.00","79037.14",""],["2018-11-09","13.640","13.200","13.640","13.040","32583231.00",{},"0.00","43127.03",""],["2018-11-12","13.380","13.140","13.560","13.100","21941098.00",{},"0.00","29218.50",""],["2018-11-13","12.840","13.300","13.360","12.740","35447436.00",{},"0.00","46509.81",""],["2018-11-14","13.200","13.160","13.340","13.100","12335258.00",{},"0.00","16268.31",""],["2018-11-15","13.280","13.060","13.340","12.800","34068658.00",{},"0.00","44253.15",""],["2018-11-16","13.100","12.940","13.200","12.800","20361231.00",{},"0.00","26313.07",""],["2018-11-19","13.000","13.600","13.700","12.960","49897906.00",{},"0.00","66787.14",""],["2018-11-20","13.660","14.740","14.800","13.340","158416525.00",{},"0.00","225638.77",""],["2018-11-21","14.500","14.840","15.160","14.300","78620564.00",{},"0.00","116253.16",""],["2018-11-22","14.960","14.320","15.000","14.260","34210705.00",{},"0.00","49725.83",""],["2018-11-23","14.320","14.440","14.440","14.080","30412700.00",{},"0.00","43265.40",""],["2018-11-26","14.500","14.300","14.560","14.180","23313991.00",{},"0.00","33443.10",""],["2018-11-27","14.220","13.820","14.380","13.740","38513213.00",{},"0.00","53642.02",""],["2018-11-28","13.940","14.500","14.640","13.940","52406420.00",{},"0.00","75251.45",""],["2018-11-29","14.700","14.200","14.860","14.040","39356934.00",{},"0.00","56590.30",""],["2018-11-30","14.300","14.280","14.400","14.160","21143591.00",{},"0.00","30285.22",""],["2018-12-03","14.800","14.860","14.980","14.720","44197080.00",{},"0.00","65681.35",""],["2018-12-04","14.940","14.640","14.940","14.420","32211993.00",{},"0.00","47099.03",""],["2018-12-05","14.380","14.300","14.380","14.140","38493584.00",{},"0.00","55383.54",""],["2018-12-06","14.100","14.000","14.180","13.800","33335368.00",{},"0.00","46487.48",""],["2018-12-07","13.960","13.640","14.040","13.020","44991040.00",{},"0.00","60676.76",""],["2018-12-10","13.500","13.280","13.500","13.160","21474200.00",{},"0.00","28468.47",""],["2018-12-11","13.260","13.380","13.500","13.200","12935341.00",{},"0.00","17267.28",""],["2018-12-12","13.500","13.520","13.720","13.440","19134630.00",{},"0.00","25962.52",""],["2018-12-13","13.700","13.760","13.820","13.500","12363996.00",{},"0.00","16941.13",""],["2018-12-14","13.780","13.540","13.780","13.480","12573551.00",{},"0.00","17047.43",""],["2018-12-17","13.540","13.520","13.620","13.300","9441591.00",{},"0.00","12720.73",""],["2018-12-18","13.360","13.260","13.480","13.020","22061077.00",{},"0.00","29111.32",""],["2018-12-19","13.200","13.260","13.320","13.100","12041587.00",{},"0.00","15890.21",""],["2018-12-20","13.140","13.080","13.180","12.700","32211712.00",{},"0.00","41447.47",""],["2018-12-21","12.900","13.680","13.680","12.680","49668836.00",{},"0.00","66056.93",""],["2018-12-24","13.420","13.160","13.420","13.040","10519067.00",{},"0.00","13826.62",""],["2018-12-27","13.160","12.920","13.300","12.860","16268154.00",{},"0.00","21189.31",""],["2018-12-28","13.000","12.940","13.160","12.840","18540002.00",{},"0.00","24004.82",""],["2018-12-31","13.100","12.920","13.100","12.840","11246279.00",{},"0.00","14540.18",""],["2019-01-02","12.980","12.200","12.980","12.180","32515761.00",{},"0.00","40045.46",""],["2019-01-03","12.280","11.760","12.320","11.760","38910146.00",{},"0.00","46264.61",""],["2019-01-04","11.660","11.960","12.040","11.500","25943844.00",{},"0.00","30771.38",""],["2019-01-07","12.320","12.000","12.380","11.960","28376962.00",{},"0.00","34329.24",""],["2019-01-08","12.160","11.100","12.160","11.060","91106400.00",{},"0.00","103413.59",""],["2019-01-09","10.500","10.340","11.100","10.340","240922422.00",{},"0.00","257271.04",""],["2019-01-10","9.630","9.970","10.040","9.440","376414318.00",{},"0.00","357023.18",""],["2019-01-11","10.180","10.340","10.520","10.000","126655283.00",{},"0.00","130595.59",""],["2019-01-14","10.420","10.020","10.480","10.000","54264395.00",{},"0.00","54919.01",""],["2019-01-15","10.060","9.960","10.160","9.830","82269650.00",{},"0.00","82243.24",""],["2019-01-16","9.700","9.700","9.940","9.590","367223812.00",{},"0.00","351005.25",""],["2019-01-17","9.810","9.740","9.950","9.670","81046985.00"

以致出現報錯

**Comment by KitKanWong** [comment]
@shidenggui

**Comment by shidenggui** [comment]
抱歉，港股日 K 是另外一个开发者贡献的，我对其中不是很了解，目前只能看有没有了解的人嫩帮助修复下

**Comment by KitKanWong** [comment]
@wangyu190810

**Comment by wangyu190810** [comment]
@KitKanWong  已经修复了，等待合并就可以使用。或者使用我都分支也可以。
