### ISSUE TITLE
package aiohttp got an error

### ISSUE THREAD

**Issue by patrickhl** [shidenggui/easyquotation#82]
ERROR: Package 'aiohttp' requires a different Python: 3.5.2 not in '>=3.5.3'
This shouldn't happen, please check the version dependency.
And
Do you have moneyflow data from tencent?

Thanks.
/Patrick

**Comment by shidenggui** [comment]
close by d2930a035e2d5ea1c2fcbaf1a4cb7a0e94c935ae
