### ISSUE TITLE
easyquotation.update_stock_codes() 报错

### ISSUE THREAD

**Issue by r41350** [shidenggui/easyquotation#85]
很长时间了，突然某天报错，再也没有好过
PermissionError                           Traceback (most recent call last)
<ipython-input-13-e5ac814f06ae> in <module>
----> 1 easyquotation.update_stock_codes()

C:\ProgramData\Anaconda3\lib\site-packages\easyquotation\helpers.py in update_stock_codes()
     12     response = requests.get("http://www.shdjt.com/js/lib/astock.js")
     13     stock_codes = re.findall(r"~(\d+)`", response.text)
---> 14     with open(STOCK_CODE_PATH, "w") as f:
     15         f.write(json.dumps(dict(stock=stock_codes)))
     16     return stock_codes

PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\easyquotation\\stock_codes.conf'

**Comment by shidenggui** [comment]
你的目录权限问题，可以尝试用管理员允许 Python 脚本
