### ISSUE TITLE
沪深 A 股部分股票缺少行情数据

### ISSUE THREAD

**Issue by thecodeway** [shidenggui/easyquotation#89]
quotation = easyquotation.use('sina')
snapshot = quotation.market_snapshot(prefix=True)
此处获取的股票代码 和我 从 其他地方获取的沪深全 A 股票列表进行比对, 发现少了两百多支股的行情数据(抽检几只看了新浪是有数据,在正常交易的), 目前发现缺少行情的股票代码列表数据如下:

sz002977
sz002978
sh688513
sz300891
sh603950
sh605003
sz300863
sh605118
sh688165
sh688338
sh688189
sz300888
sh688286
sh688536
sz300858
sh605050
sz300865
sz300852
sh601702
sh688186
sh603195
sh688390
sh688086
sh605128
sz002975
sh688185
sh603719
sz300872
sh688377
sh601778
sh688215
sh603221
sh688309
sz300885
sh688256
sz002999
sh688077
sh688080
sh688222
sz003008
sh688090
sh605108
sz300838
sz002984
sh688055
sz300853
sz003007
sz300856
sz003009
sh688157
sz300819
sh688208
sh605288
sz300859
sh688518
sz300839
sz002982
sh688177
sz002992
sh688004
sh605009
sh603439
sh688589
sh603087
sz300893
sh603290
sh688519
sz300868
sz002976
sh688588
sz300877
sh688229
sz300846
sh688559
sh603155
sz300816
sh688418
sh605158
sh603392
sh605166
sh605366
sh688312
sh688085
sh688577
sh605178
sh688556
sz300855
sh688106
sh603408
sh688398
sz300886
sz002985
sh688488
sh603948
sh688408
sh601696
sz300825
sh600918
sh688569
sh688567
sh601827
sz002996
sh688228
sz002989
sh688027
sz300835
sh688051
sh603112
sz300848
sz300880
sz300843
sz300881
sz300826
sh688301
sh688056
sh688289
sz002997
sh603682
sh688379
sz300851
sh688017
sh688393
sh688360
sh605199
sh603949
sz300818
sz300817
sz300829
sh688599
sz300883
sh601609
sh605100
sh688526
sh600956
sz300871
sh688550
sh688520
sh605088
sz300847
sz300867
sz002993
sz300841
sz300860
sh688561
sz300837
sz300876
sz300866
sz300870
sz003000
sz003003
sh688558
sz300889
sh688266
sz002988
sz300828
sh688568
sh688095
sz300875
sh603212
sh688596
sh688356
sh688313
sh605006
sh688551
sz300823
sz003010
sz300836
sz300831
sz300895
sz300830
sz300833
sh603353
sh688580
sz300878
sh688200
sh688555
sh688528
sh688127
sh603095
sz300849
sh605222
sh688318
sh688060
sh688169
sh605123
sh688050
sz003002
sh688466
sh605116
sz300869
sh688335
sz003006
sh688069
sh688156
sh688365
sz300824
sh688336
sh605399
sz002995
sz300890
sh605188
sh688505
sh605369
sh605255
sh688981
sz300873
sh605388
sh688155
sh688233
sh601456
sh688065
sz300892
sz002983
sh688159
sz300820
sz002998
sh688339
sz300850
sz002991
sh605318
sz300815
sh688516
sh605333
sz300857
sz002981
sz300861
sh688500
sh603931
sz300845
sh688277
sh688298
sh688126
sh688579
sh688180
sh605358
sz300840
sh688598
sh688508
sh605168
sh688396
sh605008
sz002986
sz002987
sz003005
sz002979
sh601399
sh605066
sz300821
sz300822
sh688311
sh603893
sh688600
sz300864
sh688096
sh688521
sz002980
sz002990
sh688026
sh688586
sh688378
sz300842
sh688566
sz300882
sz300827
sh603565
sh605198
sz300879
sh605001
sz300862
sz300832
sz300887

**Comment by thecodeway** [comment]
如果是 受限于 接口整体的体量大小做了裁剪,          可以去掉一些相对无关紧要的以腾出空间, 比如: sz200:B股、sh900:沪B股、sz1 开头的等等
最重要的数据应该是 沪深全 A, 其次 相关指数和 ETF
B股基本没什么人关注

**Comment by shidenggui** [comment]
先尝试更新股票代码
easyquotation.update_stock_codes()
