### ISSUE TITLE
请问，能否加入“换手率”的信息？

### ISSUE THREAD

**Issue by P-Rainbow** [shidenggui/easyquotation#95]
非常感谢作者的辛勤劳动和无私分享。

个股实时行情页面有“换手率”这项信息，但是我试过 新浪 和 腾讯 的接口，均无法获得此项信息。

请问能否将“换手率”的信息加入？谢谢！

**Comment by harryhan1989** [comment]
新浪接口没有换手率，这是新浪网站中那是定时刷新接口没有，无法解决，不过换手率是可以通过流通股计算而来，这个接口主要是能高频率刷新全部数据。腾讯的那个接口好像是有的相应数据的，但是腾讯的接口速度太慢，实时要求高就用sina接口，然后定时用腾讯接口中对应数据补充

**Comment by P-Rainbow** [comment]
谢谢回复！

**Comment by bigbigbigfish** [comment]
turnover就是换手率
