### ISSUE TITLE
新浪行情无法获取了

### ISSUE THREAD

**Issue by Wendroff** [shidenggui/easyquotation#99]
从2021-05-14开始，新浪行情突然就没办法获取了

**Comment by shidenggui** [comment]
测试正常，请提供更多信息

**Comment by Wendroff** [comment]
我发现了，好像是禁止国外访问了，我换了国内代理，可以了
    
        
            
                
                    
                        
                    
                    
                        
                            王哲夫
                            
                            
                                
                                    ***@***.***
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
            在2021年05月17日 20:32，shidenggui 写道： 

测试正常，请提供更多信息



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/shidenggui/easyquotation/issues/99#issuecomment-842286829",

"url": "https://github.com/shidenggui/easyquotation/issues/99#issuecomment-842286829",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
